name: variables
on: push

env:
  root_env_variable: Hi!! ğŸ¤

jobs:
   job_1:
    runs-on: ubuntu-latest
    env:
      job_env_variable: Good Morning ğŸ”…
    steps:
      - name: "JOB 1"
        run: echo "$root_env_variable $First_Name $job_env_variable"
        env:
          First_Name: user 1
          
